-- DropForeignKey
ALTER TABLE "IPRecord" DROP CONSTRAINT "IPRecord_userId_fkey";

-- AlterTable
ALTER TABLE "IPRecord" ALTER COLUMN "userId" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "userId" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "IPRecord" ADD CONSTRAINT "IPRecord_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("userId") ON DELETE RESTRICT ON UPDATE CASCADE;
